name: myenv

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8  # 선택된 Python 버전
  - pytorch=2.*
  - torchvision=0.*
  - lightning=2.*
  - torchmetrics=0.*
  - hydra-core=1.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  - cmake>=3.18
  - scikit-build>=0.11.1
  - pybind11>=2.6.2
  - scipy
  - requests>=2.25,<3
  - numpy>=1.22
  - protobuf>=4.21.6
  - matplotlib>=3.0
  - pip>=23
  - pip:
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
