
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train: ## Train the model
	python src/train.py

# Existing SALMON-main Makefile commands
...

# Environment variable for MKL
MKLROOT ?= /path/to/mkl  # 필요에 따라 MKL의 경로를 설정하세요

# Add aihwkit build commands
.PHONY: build_aihwkit build_aihwkit_mkl build_aihwkit_cuda

build_aihwkit:
	python setup.py build_ext -j8 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE --inplace ${flags}

build_aihwkit_mkl:
	make build_aihwkit flags="-DRPU_BLAS=MKL -DINTEL_MKL_DIR=${MKLROOT} ${flags}"

build_aihwkit_cuda:
	make build_aihwkit_mkl flags="-DUSE_CUDA=ON ${flags}"

# Clean command for aihwkit
clean_aihwkit:
	python setup.py clean
	rm -rf _skbuild
	rm -f src/aihwkit/simulator/rpu_base.*.so

# You can also add additional commands related to aihwkit if necessary
...

# End of Makefile
