wandb_version: 1

N_CLASSES:
  value: 8
alpha:
  value: 0.5044114254845251
autoaugment:
  value: 'false'
batch_size:
  value: 79
batchsize:
  value: 179
block:
  value: BasicBlock
callbacks.early_stopping._target_:
  value: lightning.pytorch.callbacks.EarlyStopping
callbacks.early_stopping.check_finite:
  value: 'false'
callbacks.early_stopping.mode:
  value: max
callbacks.early_stopping.monitor:
  value: val/acc
callbacks.early_stopping.patience:
  value: 132
callbacks.early_stopping.strict:
  value: 'true'
callbacks.early_stopping.verbose:
  value: 'false'
callbacks.model_checkpoint._target_:
  value: lightning.pytorch.callbacks.ModelCheckpoint
callbacks.model_checkpoint.auto_insert_metric_name:
  value: 'true'
callbacks.model_checkpoint.dirpath:
  value: ${paths.output_dir}/checkpoints
callbacks.model_checkpoint.filename:
  value: epoch_{epoch:03d}
callbacks.model_checkpoint.mode:
  value: max
callbacks.model_checkpoint.monitor:
  value: val/acc
callbacks.model_checkpoint.save_last:
  value: 'false'
callbacks.model_checkpoint.save_top_k:
  value: 1
callbacks.model_checkpoint.save_weights_only:
  value: 'false'
callbacks.model_checkpoint.verbose:
  value: 'true'
callbacks.model_summary._target_:
  value: lightning.pytorch.callbacks.RichModelSummary
callbacks.model_summary.max_depth:
  value: 0
callbacks.rich_progress_bar._target_:
  value: lightning.pytorch.callbacks.RichProgressBar
compile:
  value: 'false'
data._target_:
  value: src.data.cifar10_datamodule.CIFAR10DataModule
data.batch_size:
  value: 121
data.data_dir:
  value: ${paths.data_dir}
data.num_workers:
  value: 6
data.pin_memory:
  value: 'true'
data_dir:
  value: /root/SALMON/data/
dataset:
  value: cifar10
dataset_path:
  value: data
epoch:
  value: 400
extras.enforce_tags:
  value: 'true'
extras.ignore_warnings:
  value: 'false'
extras.print_config:
  value: 'true'
feature_loss_coefficient:
  value: 0.18109344624024665
init_lr:
  value: 0.09537866895536408
loss_coefficient:
  value: 0.5836750462656497
model:
  value: resnet10
model._target_:
  value: src.models.exp2_resnet_SD_digit.SalmonLitModule
model.batch_size:
  value: 22
model.compile:
  value: 'true'
model.integrated_resnet._target_:
  value: src.models.components.salmon.IntegratedResNet
model.integrated_resnet.architecture:
  value: resnet10
model.integrated_resnet.num_classes:
  value: 15
model.net._target_:
  value: src.models.components.salmon.IntegratedResNet
model.net.num_classes:
  value: 17
model.num_workers:
  value: 8
model.optimizer._partial_:
  value: 'true'
model.optimizer._target_:
  value: torch.optim.Adam
model.optimizer.lr:
  value: 0.039723699322014
model.scheduler._partial_:
  value: 'false'
model.scheduler._target_:
  value: torch.optim.lr_scheduler.StepLR
model.scheduler.factor:
  value: 0.14851596981010343
model.scheduler.gamma:
  value: 0.1976209557080328
model.scheduler.mode:
  value: min
model.scheduler.patience:
  value: 100
model.scheduler.step_size:
  value: 49
model/params/total:
  value: 6639401
model/params/trainable:
  value: 10510305
num_workers:
  value: 3
p_max:
  value: 1206
pin_memory:
  value: 'true'
seed:
  value: 23931
task_name:
  value: train
temperature:
  value: 79.98118545677107
trainer._target_:
  value: lightning.pytorch.trainer.Trainer
trainer.accelerator:
  value: gpu
trainer.check_val_every_n_epoch:
  value: 1
trainer.default_root_dir:
  value: ${paths.output_dir}
trainer.deterministic:
  value: 'false'
trainer.devices:
  value: 2
trainer.gradient_clip_val:
  value: 0.8335696865815835
trainer.max_epochs:
  value: 245
trainer.min_epochs:
  value: 6
