_target_: src.models.exp4_1_module.SalmonLitModule

# Define the IntegratedResNet configuration
integrated_resnet:
  _target_: src.models.components.exp4_model.IntegratedResNet
  architecture: "resnet18"
  num_classes: 10
  rpu_config:
    _target_: aihwkit.simulator.presets.IdealizedPreset
    
# Optimizer settings
optimizer:
  lr: 0.01
  betas: [0.9, 0.999]
  eps: 1.0e-08
  weight_decay: 0.0
  amsgrad: false


# Additional hyperparameters
compile: false
model: "resnet18"
dataset: "cifar10"
epoch: 300
loss_coefficient: 0.5
feature_loss_coefficient: 0.03
dataset_path: "data"
autoaugment: False
temperature: 3
batchsize: 128
init_lr: 0.1
N_CLASSES: 10
block: BasicBlock
alpha: 0.3
p_max: 10000
opt_config : "AnalogAdam"
sch_config : "off-schedule"