_target_: src.models.exp4_2_module.SalmonLitModule

# Define the IntegratedResNet configuration
integrated_resnet:
  _target_: src.models.components.exp4_model.IntegratedResNet
  architecture: "resnet18"
  num_classes: 10
  rpu_config:
    _target_: aihwkit.simulator.presets.IdealizedPreset
    
# Optimizer settings
optimizer:
  lr: 0.01
  weight_decay: 0.0
  # SGD를 사용하므로, Adam에 특화된 betas, eps, amsgrad 매개변수는 제거
  momentum: 0.9  # SGD에 자주 사용되는 momentum 매개변수 추가
  # 필요한 경우 dampening과 nesterov 매개변수를 추가할 수 있습니다. 예시에서는 생략
  # dampening: 0  # 선택적
  # nesterov: False  # 선택적


# Additional hyperparameters
compile: false
model: "resnet18"
dataset: "cifar10"
epoch: 300
loss_coefficient: 0.5
feature_loss_coefficient: 0.03
dataset_path: "data"
autoaugment: False
temperature: 3
batchsize: 128
init_lr: 0.1
N_CLASSES: 10
block: BasicBlock
alpha: 0.3
p_max: 10000
opt_config : "AnalogSGD"
sch_config : "off-schedule"