_target_: src.models.exp4_module.SalmonLitModule

# Define the IntegratedResNet configuration
integrated_resnet:
  _target_: src.models.components.exp4_model.IntegratedResNet
  architecture: "resnet18"
  num_classes: 10
  rpu_config:
    _target_: aihwkit.simulator.presets.IdealizedPreset
    
# Optimizer settings
optimizer:
  lr: 0.01
  betas: [0.9, 0.999]
  eps: 1.0e-08
  weight_decay: 0.0
  amsgrad: false

# Scheduler settings
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 300 # 여기서 T_max는 한 주기의 길이(epoch 수)를 의미합니다.
  eta_min: 0.00437 # 이 값은 주기의 최저점에서의 학습률을 의미합니다. 필요에 따라 조정하세요.

# Additional hyperparameters
compile: false
model: "resnet18"
dataset: "cifar10"
epoch: 300
loss_coefficient: 0.5
feature_loss_coefficient: 0.03
dataset_path: "data"
autoaugment: False
temperature: 3
batchsize: 128
init_lr: 0.1
N_CLASSES: 10
block: BasicBlock
alpha: 0.3
p_max: 10000
