_target_: src.models.exp7_6_digital_module.SalmonLitModule

# Define the IntegratedResNet configuration with EcRamPreset
integrated_resnet:
  _target_: src.models.components.exp7_6_digital_model.IntegratedResNet
  architecture: "resnet18"
  num_classes: 10
  rpu_config:
    _target_: aihwkit.simulator.configs.SingleRPUConfig
    device:
      _target_: aihwkit.simulator.presets.EcRamPresetDevice

# Optimizer settings
optimizer:
  lr: 0.01
  weight_decay: 0.0001
  momentum: 0.9
  dampening: 0
  nesterov: False

# Cosine annealing scheduler
scheduler:
  T_max: 300
  eta_min: 0.0001

# Additional hyperparameters
compile: false
model: "resnet18"
dataset: "cifar10"
epoch: 300
loss_coefficient: 0.0
feature_loss_coefficient: 0.0
dataset_path: "data"
autoaugment: False
temperature: 3
batchsize: 128
init_lr: 0.01
N_CLASSES: 10
block: BasicBlock
alpha: 0.3
p_max: 10000
opt_config: "AnalogSGD"
sch_config: "cosine"
sd_config: "true"
FC_Digit: "true"

# 5-head configuration: D1, D2, D3, D5, D6
use_all_heads: true
active_heads: ['D1', 'D2', 'D3', 'D5', 'D6']