# @package _global_

# Optimized hyperparameter search for loss_coefficient in exp7_6_digital
# Testing different loss_coefficient values to find optimal balance

defaults:
  - override /hydra/sweeper: optuna

# Choose metric to optimize
optimized_metric: "val/acc_0"

# Configure Hydra's sweeper
hydra:
  mode: MULTIRUN
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    
    # Storage for distributed optimization
    storage: null
    study_name: loss_coefficient_sweep
    n_jobs: 1
    
    # Optimization settings
    direction: maximize
    n_trials: 7  # Number of different values to test
    
    # Define search space for loss_coefficient
    params:
      model.loss_coefficient: choice(0.0, 0.01, 0.1, 0.5, 1.0, 2.0, 10.0)
    
    # Optuna specific settings
    sampler:
      _target_: optuna.samplers.GridSampler
      
    # Pruning settings (optional)
    pruner:
      _target_: optuna.pruners.MedianPruner
      n_warmup_steps: 10
      n_startup_trials: 3
      interval_steps: 1