# @package _global_

# Optuna hyperparameter optimization for ResNet models on CIFAR10
# Run command: python src/train.py -m hparams_search=mnist_optuna experiment=exp1.yaml trainer=gpu

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: "val/acc_0"

hydra:
  mode: "MULTIRUN"

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1
    direction: maximize
    n_trials: 40
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      n_startup_trials: 10

    params:

      model.loss_coefficient: interval(0.01, 1)
      model.feature_loss_coefficient: interval(0.01, 1)
      model.temperature: interval(0.1, 10)

